src/java/au/edu/uts/ass1/Controller/LoginController.java

package au.edu.uts.ass1.Controller;

import java.sql.*;
import java.util.*;
import java.util.logging.*;
import javax.enterprise.context.*;
import javax.faces.application.*;
import javax.faces.context.*;
import javax.inject.*;
import javax.naming.*;
import javax.servlet.*;
import javax.servlet.http.*;
import javax.sql.*;
import au.edu.uts.ass1.Model.AccountDTO;
import au.edu.uts.ass1.DAO.AccountDAO;

import au.edu.uts.ass1.Helper.DataStoreException;




/**
 * A backing bean used for account management in our application.
 * @author Sarthak
 * @version 1.0
 * @since 2016-08-12
 */

@Named
@RequestScoped
public class LoginController {
    
    //Fields for username and password attributes of login.
    private String username;
    private String password;
    
    //getters and setters of the fields.
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    /**
     * This method is used to control login of user by checking 
     * the user supplied username password with database.
     * @return
     * @throws DataStoreException 
     */
    public String login() throws DataStoreException {
        AccountDAO dao = new AccountDAO();
        AccountDTO user = dao.findUser(username);
        if (password.equals(user.getPassword())) {
            return "/ListEvent?faces-redirect=true";
        } else {
            showError("Incorrect username or password");
            return null;
        }
        
        
        
    }
    
    /**
     * This method is used to control the logout of the user.
     * @return
     * @throws ServletException 
     */
    public String logout() throws ServletException {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest)context.getExternalContext().getRequest();
        request.logout();
        return "/index?faces-redirect=true";
    }
    
    /**
     * Adds a message to the current faces context, so that it will appear in
     * a h:messages element.
     * @param message the text of the error message to show the user
     */
    private void showError(String message) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(message));
    }
    
}

src/java/au/edu/uts/ass1/Controller/RecordController.java
package au.edu.uts.ass1.Controller;

import java.sql.*;
import java.util.*;
import java.util.logging.*;
import javax.enterprise.context.*;
import javax.faces.application.*;
import javax.faces.context.*;
import javax.inject.*;
import javax.naming.*;
import javax.servlet.*;
import javax.servlet.http.*;
import javax.sql.*;
import javax.validation.constraints.Min;
import javax.validation.constraints.Size;
import au.edu.uts.ass1.Model.RecordDTO;
import au.edu.uts.ass1.DAO.RecordDAO;

import au.edu.uts.ass1.Helper.DataStoreException;




/**
 * A backing bean used for record management in our application.
 * @author Sarthak
 * @version 1.0
 * @since 2016-08-12
 */
@Named
@RequestScoped
public class RecordController {
    
    //various fieds for type record.
    private String event;
    private String organizer;
    private String location;
    private String date;

    
    //getters and setters
    @Size(min=1)
    public String getEvent() {
        return event;
    }

    public void setEvent(String event) {
        this.event = event;
    }
    @Size(min=1)
    public String getOrganizer() {
        return organizer;
    }

    public void setOrganizer(String organizer) {
        this.organizer = organizer;
     
    }
    
    @Size(min=1)
    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }
    
    @Size(min=1)
    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }
    
    
    public ArrayList<RecordDTO> getAllEvents() throws au.edu.uts.ass1.Helper.DataStoreException {
        return new RecordDAO().findAll();
    }
    
    
//    public RecordDTO getEvents() throws au.edu.uts.ass1.records.DataStoreException {
//        return new RecordDAO().findEvent(event);
//    }
    
    /**
     *This method is used to invoke the insert method in DAO, which
     * creates an record in the database
     * @return String This returns to ListEvent jsf if the data is successfully created.
     * @throws au.edu.uts.ass1.records.DataStoreException
     */
    public String create() throws au.edu.uts.ass1.Helper.DataStoreException {
     
        RecordDAO dao = new RecordDAO();
        dao.insert(event,organizer,location,date);
        
        return "/ListEvent?faces-redirect=true";
    }
    
    /**
     *This method is used to invoke the update method in DAO, which
     * updates a record in the database
     * @return String This returns to ListEvent jsf if the data is successfully created.
     * @throws au.edu.uts.ass1.records.DataStoreException
     */
    public String edit() throws au.edu.uts.ass1.Helper.DataStoreException {
     
        RecordDAO dao = new RecordDAO();
        dao.update(event,organizer,location,date);
        
        return "/ListEvent?faces-redirect=true";
    }
    
    /**
     *This method is used to invoke the delete method in DAO, which
     * deletes a record in the database
     * @return String This returns to ListEvent jsf if the data is succesfully created.
     * @throws au.edu.uts.ass1.records.DataStoreException
     */
    public String delete() throws au.edu.uts.ass1.Helper.DataStoreException {
        
        RecordDAO dao = new RecordDAO();
        dao.remove(event);
       
        return "/ListEvent?faces-redirect=true";
  }
    

//method to create a record
    
}

web/CreateEvent.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>TRG Event</title>
        <h:outputStylesheet library ='css'  name ='stylecss.css'/>
    </h:head>
    <h:body>
        <div class='wrapper'>
            <h2>Add an Upcoming Event</h2>
        
        <h:form>
            <p>
                <label>EventName:
                    <h:inputText
                        id ="event"
                        value="#{recordController.event}"
                        validatorMessage="You must enter a name"/>
                </label>
                <h:message for="name"/>
            </p>
            <p>
                <label>Organizer:
                    <h:inputText 
                        id= "organizer"
                        value="#{recordController.organizer}"
                        validatorMessage="You must enter a organizer"/>
                </label>
                <h:message for="organizer"/>
            </p>
            <p>
                <label>Location:
                    <h:inputText 
                        id="location"
                        value="#{recordController.location}"
                        validatorMessage="You must enter a location"/>
                </label>
                <h:message for="location"/>
            </p>
            <p>
                <label>Date:
                    <h:inputText
                        id="time"
                        value="#{recordController.date}"
                        validatorMessage="You must enter a date"/>
                </label>
                <h:message for="time"/>
            </p>
            <p>
                <h:commandButton value="Save" action="#{recordController.create}"/>
                
            </p>
        </h:form>
        
        </div>
    </h:body>
</html>

web/DeleteEvent.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <f:metadata>

    </f:metadata>
    <h:head>
        <title>Waiting List</title>
    </h:head>
    <h:body>
        <h1>Delete Group</h1>
        <p>Are you sure you want to delete?</p>
        <h:form>
            <p>
                <label>Event Name: 
                    <h:inputText value="#{recordController.event}"
                                 validatorMessage="You must enter a event name"/>
                </label>
            </p>
            
            <p>
                <h:commandButton value="Delete" action="#{recordController.delete()}"/>
            </p>
        </h:form>
    </h:body>
</html>

web/EditEvent.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <f:metadata>
        
    </f:metadata>
    <h:head>
        <title>TRG Event</title>
    </h:head>
    <h:body>
        <h1>Edit Event</h1>
        <h:form>
            <p>
                <label>EventName:
                    <h:inputText
                        id ="event"
                        value="#{recordController.event}"/>
                </label>
            </p>
            <p>
                <label>Organizer:
                    <h:inputText 
                        id= "organizer"
                        value="#{recordController.organizer}"/>
                </label>
            </p>
            <p>
                <label>Location:
                    <h:inputText 
                        id="location"
                        value="#{recordController.location}"/>
                </label>
            </p>
            <p>
                <label>Date:
                    <h:inputText
                        id="date"
                        value="#{recordController.date}"/>
                </label>
            </p>
            <p>
                <h:commandButton value="Save" action="#{recordController.edit}"/>
                
            </p>
        </h:form>
    </h:body>
</html>

web/ListEvent.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>List Events</title>
        
        <h:outputStylesheet library ='css'  name ='stylecss.css'/>
    </h:head>
    <h:body>
        <h:form>
        <div class="topright"> Welcome #user <h:commandButton value="Logout" action="#{loginController.logout}"/> </div>
        </h:form>
        <div class ='wrapper'>
        <h1>List of upcoming Events for TRG</h1>
        <h:link value="Create Event" outcome="/CreateEvent?faces-redirect=true"/>
        <h:dataTable var="row" styleClass="order-table" value="#{recordController.allEvents}">
            <h:column>
                <f:facet name="header">
                    Event
                </f:facet>
                <h:outputText value="#{row.event}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Organizer
                </f:facet>
                <h:outputText value="#{row.organizer}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Location
                </f:facet>
                <h:outputText value="#{row.location}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Date/Time
                </f:facet>
                <h:outputText value="#{row.date}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Action
                </f:facet>
                

                
                <h:link value="Edit" outcome="EditEvent">
                    <f:param name="index" value="#{row.event}"/>
                </h:link>
                
                <h:link value="Delete" outcome="DeleteEvent">
                    <f:param name="index" value="#{row.event}"/>
                </h:link>-->
                
            </h:column>
        </h:dataTable>  
        </div>
    </h:body>
</html>

web/ViewEvent.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>TRG Event</title>
        <h:outputStylesheet library ='css'  name ='stylecss.css'/>
    </h:head>
    <h:body>
        <div class ='wrapper'>
            <h:form>
        <h:dataTable var="row" styleClass="order-table" value="#{recordController.events}">
            <h:column>
                <f:facet name="header">
                    Event
                </f:facet>
                <h:outputText value="#{event}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Organizer
                </f:facet>
                <h:outputText value="#{row.organizer}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Location
                </f:facet>
                <h:outputText value="#{row.location}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Date/Time
                </f:facet>
                <h:outputText value="#{row.date}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Action
                </f:facet>
                <h:link value="View" outcome="ViewEvent">
                    <f:param name="index" value="#{row.event}"/>
                </h:link>
            </h:column>
        </h:dataTable>  
            <h:commandButton value="OK" action="ListEvent"/>
            </h:form>
        </div>
    </h:body>
</html>

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>TRG EVENTS</title>
        <h:outputStylesheet library ='css'  name ='stylecss.css'/>
    </h:head>
    <h:body>
        <div class ='listing'>
            <h1> Welcome to TRG's EVENTS page</h1>
        <h:form>
            <p>
                <label>Username:
                    <h:inputText value="#{loginController.username}"/>
                </label>
            </p>
            <p>
                <label>Password:
                    <h:inputSecret value="#{loginController.password}"/>
                </label>
            </p>
            <p>
                <h:commandButton value="Log In" action="#{loginController.login}"/>
                
            </p>
        </h:form>
        </div>
       
    </h:body>
</html>